### ISSUE TITLE
How ofter are the snippets regenerated?

### ISSUE THREAD

**Issue by zioalex** [damienaicheh/azure-devops-snippets-generator#4]
I do not find how do you manage the snippets (re)generation.
Does is happen at every restart, once a day...or never.
Would be great to have some more details about it.
Thanks

**Comment by damienaicheh** [comment]
It's not done automatically for now, the idea will be to setup the pipeline to publish it every month to the market for example. I didn't spend time to do it for now.

**Comment by zioalex** [comment]
I can help with the automation.
Please document how to run the update.

**Comment by damienaicheh** [comment]
Just need to run the publish script and increase the version number and upadte the readme but to upload the extension this will need my account. I will try to do it soon.

**Comment by doggy8088** [comment]
@damienaicheh Are you already setup CI/CD for your extension?

**Comment by damienaicheh** [comment]
No, didn't have time for it.
